tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "mas"
brew "git-crypt"
brew "gnupg"
brew "pure"
brew "gh"
brew "gti" # lol
brew "htop"
brew "jq"
brew "ranger"
brew "tree"
brew "tmux"
brew "watch"
brew "curl"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "cleanshot"
cask "docker"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "google-chrome"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
brew "thefuck"
cask "monodraw"
cask "postico"
cask "rectangle"
cask "obs"
cask "signal"
cask "whatsapp"
cask "sketch"
cask "slack"
cask "spotify"
cask "synology-drive"
cask "tableplus"
cask "vlc"
cask "vim"
cask "zoom"
mas "Keynote", id: 409183694
mas "Pixelmator", id: 407963104
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
