tap "homebrew/bundle"
brew "go"
brew "kubernetes-cli"
brew "k9s"
brew "mas"
brew "direnv"
brew "gnupg"
brew "pure"
brew "gh"
brew "gti" # lol
brew "htop"
brew "jq"
brew "ranger"
brew "tree"
brew "tmux"
brew "watch"
brew "curl"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "fzf"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "cleanshot"
cask "firefox"
cask "google-chrome"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
brew "thefuck"
cask "monodraw"
cask "obs"
cask "whatsapp"
cask "sketch"
cask "slack"
cask "spotify"
cask "vlc"
cask "vim"
cask "zoom"
cask "visual-studio-code"
mas "Pixelmator", id: 407963104
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
